;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		ace-jump-word-mode
		beginning-of-visual-line
		c-electric-semi&comma
		c-electric-slash
		comment-region
		complete-symbol
		evil-append
		evil-append-line
		evil-backward-char
		evil-backward-word-begin
		evil-delete
		evil-delete-char
		evil-end-of-line
		evil-exit-visual-state
		evil-first-non-blank
		evil-force-normal-state
		evil-forward-WORD-end
		evil-forward-word-begin
		evil-forward-word-end
		evil-inner-bracket
		evil-insert
		evil-jump-item
		evil-next-line
		evil-normal-state
		evil-paste-after
		evil-previous-line
		evil-scroll-page-down
		evil-visual-char
		evil-yank
		indent-for-tab-command
		keyboard-escape-quit
		org-force-self-insert
		org-insert-heading-respect-content
		org-metaleft
		org-self-insert-command
		smex-major-mode-commands
		))

(setq mc/cmds-to-run-once
      '(
		abort-recursive-edit
		evil-delete-backward-char-and-join
		evil-forward-char
		evil-mouse-drag-region
		evil-search-next
		goto-line
		helm-M-x
		ibuffer
		isearch-delete-char
		isearch-forward-regexp
		js2-mode-show-node
		neotree-toggle
		select-window-4
		yas-expand
		zap-up-to-char
		))
