;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        ace-jump-word-mode
        c-electric-semi&comma
        comment-region
        complete-symbol
        evil-append
        evil-backward-char
        evil-delete-char
        evil-end-of-line
        evil-exit-visual-state
        evil-force-normal-state
        evil-forward-word-end
        evil-insert
        evil-next-line
        evil-normal-state
        evil-paste-after
        evil-previous-line
        evil-visual-char
        evil-yank
        keyboard-escape-quit
        org-force-self-insert
        org-self-insert-command
        ))

(setq mc/cmds-to-run-once
      '(
        evil-forward-char
        evil-search-next
        goto-line
        ibuffer
        isearch-delete-char
        isearch-forward-regexp
        js2-mode-show-node
        neotree-toggle
        select-window-4
        yas-expand
        zap-up-to-char
        ))
